[build]
  base = "unified-erp"
  command = "npm install --no-audit --no-fund && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"
